###
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type:  application/json

{
  "name":"Test3",
  "price": 20
}

###
GET http://localhost:3000/products/661e898cfea23e5a20fe331b
Content-Type: application/json


###
Put http://localhost:3000/products/661e898cfea23e5a20fe331b
Content-Type: application/json

{
  "price":23
}

###
Delete http://localhost:3000/products/661e8983fea23e5a20fe3317

