export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

import React from 'react'

export default function About() {
  return (
    <>
      <h1>About</h1>
    </>
  )
}
