###
GET http://localhost:3000/api/todos
Content-Type: application/json
Authorization: Bearer 1234

###
DELETE http://localhost:3000/api/todos
Content-Type: application/json

{
  "id": "1"
}


###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "userId": "11",
  "title": "New Todo",
  "completed": "false"
}


###
PUT http://localhost:3000/api/todos
Content-Type: application/json

{
  "id": "1",
  "completed": "true"
}


###
GET http://localhost:3000/api/todos/3
