###
GET http://localhost:3000/api/users


###
GET http://localhost:3000/api/users/67957fc99761e6c352383056


###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username":"Mesto Kaya",
  "password":"909090"
}

###
PUT http://localhost:3000/api/users?id=67957fc99761e6c352383056
Content-Type: application/json

{
  "password":"6666"
}

###
DELETE http://localhost:3000/api/users?id=679585b0daac2ea9dfdf5c1d