

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div>
     <h2>Admin Layout</h2>
     <main>
     {children}
     </main>
   </div>
  );
}
