export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Navbar from "../../components/navbar"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <Navbar />
      <h2>Main Layout</h2>
      {children}
      </body>
    </html>
  )
}
