export const metadata = {
  title: "User Details",
  description: "Generated by create next app",
};

import { getUsers } from "../page"
import Backbtn from '../../../components/backbtn/page'
export default async function Details({params}) {
  const {id} = await params
  const users = await getUsers()
  const user = users.filter(item => item.id == id)[0]
  return (
    <>
      <h1>User Details</h1>
      <ul>
          <li>{user.id}</li>
          <li>{user.name}</li>
          <li>{user.email}</li>
      </ul>
      <Backbtn />
    </>
  )
}

export async function generateStaticParams() {
  const users = await getUsers()
  return users.map(item => ({id: `${item.id}`}))
}