import "../globals.css";
import Navbar from "../copmonents/navbar";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <main className="router">
        {children}
        </main>
      </body>
    </html>
  );
}
