export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Navbar from "./components/navbar"
import "./main.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
      <Navbar />
      <main className="router">{children}</main>
      </body>
    </html>
  )
}
