export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

async function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

export default async function Home() {
 await delay(1000)
  return (
    <div>
      <h1>Home</h1>
    </div>
  );
}
