import Navbar from "@/components/navbar";
import "../globals.css";
export const metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        <main className="router">
        {children}
        </main>
      </body>
    </html>
  );
}
