import "@/global.css";

export const metadata = {
  title: "Next App / Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <main className="router">
          {children}
        </main>
      </body>
    </html>
  );
}
