###
GET http://localhost:3000/api/router/test
Authorization: ""

###
POST http://localhost:3000/api/router/test
Content-Type: application/json

{
  "name" : "mesto",
  "password": "9090"
}


###
PUT http://localhost:3000/api/router/test/1


###
DELETE http://localhost:3000/api/router/test/1
