const os = require('os')

console.log('platform' +' '+ os.platform())
console.log('arch' +' '+ os.arch())
console.log('cpus-------------------------')
console.log(os.cpus())
console.log('totalmem' +' '+ (os.totalmem() / (1024*1024*1024)).toFixed(0) +' '+ 'GB')
console.log('freemem' +' '+ (os.freemem() / (1024*1024*1024)).toFixed(0) +' '+ 'GB')
console.log('homedir' +' '+ os.homedir())
console.log('userinfo----------------------')
console.log(os.userInfo())
console.log('uptime' +' '+ os.uptime())
console.log('type' +' '+ os.type())
console.log('release' +' '+ os.release())